name: RealDistantCommands
main: fr.crafter.tickleman.realdistantcommands.RealDistantCommandsPlugin
version: 1.01
website: http://plugins.crafter.fr/tickleman/RealDistantCommands/
author: tickleman
